### ISSUE TITLE
Make it so you can ding and sing from the web UI

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pi-bell-slapper#11]
A few feature requests:

  - [x] Make the 'success' alert for dinging the bell dismissible.
  - [x] Make the 'success' alert automatically hide after 3 seconds.
  - [x] Add a 'Ding + Sound' button so you can both ding and play a sound if configured using `config.yml`

For deployment, I'll need to run `sudo apt install php-yaml` on my production Clarence unit, and pull all the latest data, then maybe restart `apache2`.

**Comment by geerlingguy** [comment]
![fade-it](https://user-images.githubusercontent.com/481677/228963561-873d2d1a-0a0b-4e04-bc59-ebce899ef5c2.gif)

**Comment by geerlingguy** [comment]
For the sound, I'm getting the following on a Pi I'm testing on that doesn't actually have a sound device integrated:

```
==> error.log <==
Failed to create secure directory (/var/www/.config/pulse): No such file or directory
Failed to create secure directory (/var/www/.config/pulse): No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/home/pi/pi-bell-slapper/play_sound.py", line 32, in <module>
    play_the_sound()
  File "/home/pi/pi-bell-slapper/play_sound.py", line 23, in play_the_sound
    pygame.mixer.init()
pygame.error: No available audio device
```

I'm not sure if that first line is an error that would break anything or not (as I haven't tried this on the system that actually has the little USB sound card...), but it's something to keep in mind if it's not working. See https://unix.stackexchange.com/a/90025 for an example of a fix. I might just see about setting up pulseaudio settings for the Apache user, or system-wide.

**Comment by geerlingguy** [comment]
Added the extra option and made everything supposedly work:

<img width="566" alt="Screen Shot 2023-03-30 at 4 12 29 PM" src="https://user-images.githubusercontent.com/481677/228965762-52d19e31-5080-42bf-baf1-6bae24504cef.png">

**Comment by geerlingguy** [comment]
In production, getting:

```
Home directory not accessible: Permission denied
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/home/pi/pi-bell-slapper/play_sound.py", line 32, in <module>
    play_the_sound()
  File "/home/pi/pi-bell-slapper/play_sound.py", line 23, in play_the_sound
    pygame.mixer.init()
pygame.error: ALSA: Couldn't open audio device: No such file or directory
```

**Comment by geerlingguy** [comment]
After adding a `/etc/asound.conf` file with the same contents as the pi user's, it seems like the thing works!

```
Home directory not accessible: Permission denied
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
```

Still get 'Home directory not accessible' but that's probably just ALSA mixer attempting to load any `apache2` user overrides.
